name: Blocklist

on:
  schedule:
    - cron: '1 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate IP blocklist

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Run the script
      uses: ./
    
    - name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        git-committer-name: "GitHub Actions"
        git-committer-email: "robertoschiavone@users.noreply.github.com"
        git-user-signingkey: true
        git-commit-gpgsign: true
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
    
    - name: Commit and push 
      run: |
        git add . 
        git commit -S -m "chore: ${{ steps.date.outputs.today }} blocklist :recycle:" -m "generated"
        git push
