name: Generate blocklist

on:
  schedule:
    - cron: '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        run: |
          chmod +x ./blocklist.sh
          ./blocklist.sh

      - name: Tag branch
        run: |
          gh release delete latest --yes || true
          git tag -f latest
          git push -f origin latest
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Automated nightly build
            
            Generated on: ${{ env.RELEASE_DATE }}
          tag_name: latest
          files: blocklist.p2p
